# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.7"
  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
 install: pip install -r requirements_dev.txt

# # Command to run tests, e.g. python setup.py test
 script: 
  - python -m coverage run -m pytest
  - black --check --skip-string-normalization .

 after_success: coveralls


 notifications:
  email:
    recipients: adelle.goodwin@monash.edu
      on_success: change
      on_failure: always
